server:
  servlet:
    context-path: /api

spring:
  profiles:
    include: ${profile}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

openai:
  gpt-model: gpt-4-turbo-2024-04-09
  gpt-key: #gptkey
  gpt-url: https://api.openai.com/v1/chat/completions
  dalle-modle: dall-e-3
  dalle-key: #dalle-key
  dalle-url: https://api.openai.com/v1/images/generations
