spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "ssafypiece202@gmail.com"
    password: "zavoxtoquckuzlor"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2


aes256:
  secret: "ssafydaejeonb202finalpjtispiece!"
  iv: "keepgoingfinal!"
